### PR TITLE
Updated docs + made mpl swatch look more similar to bokeh swatch

### PR DESCRIPTION
**Pull request by story645**
Bit of all the things:
1. moved around doc & removed references to colorcet
2. added hook to customize mpl swatch to look closer to bokeh swatch
3. edited contribute doc
4. added PR template

### CODE REVIEW

**Comment by jsignell** [comment]
I'm rebasing this PR now and removing output from notebooks.

**Comment by story645** [comment]
Ack, sorry! #3 was such a mess that I forgot about this one. I can also rebase if you want.

**Comment by jsignell** [comment]
@story645 what do you think is the best way to ensure that people clear the output from the notebook before checking it in? A pre-commit hook?

**Comment by story645** [comment]
Probably, and also maybe adding it to the PR instructions and templates? I totally forgot that docs build systems run notebooks.

**Comment by jsignell** [comment]
I made the colormaps a gallery and condensed the two top level notebooks into one. Should make it easier to figure out.

**Comment by jsignell** [comment]
Deployed at https://pyviz-dev.github.io/contrib_colormaps/index.html 
Will merge when green.

**Comment by ceball** [comment]
@jsignell I just happened to notice that there are In and Out prompts:

Screenshot from 2019-11-22 19-09-22

Is that via some setting (i.e. deliberate), or has something changed...?

**Comment by jsignell** [comment]
This site is using a different theme (alabaster) than the holoviz ones (sphinx_holovix_theme). I had assumed that the prompt numbers on our holoviz sites were being hidden by the theme, rather than by nbsite.

**Comment by ceball** [comment]
Ah right, that makes sense, thanks.

**Pull request merged**
